"""empty message

Revision ID: 48f03a0302b2
Revises: 5b56e0042347
Create Date: 2023-02-08 16:20:24.937339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48f03a0302b2'
down_revision = '5b56e0042347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=120), nullable=True))
    op.drop_column('users', 'name')
    op.drop_column('users', 'address')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'email')
    op.drop_column('users', 'nome')
    # ### end Alembic commands ###
