"""empty message

Revision ID: 5b56e0042347
Revises: bde323e9d9b9
Create Date: 2023-02-08 13:45:15.333889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b56e0042347'
down_revision = 'bde323e9d9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('linkedin_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste',
    sa.Column('Field_1', mysql.TINYINT(), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
