"""empty message

Revision ID: 8c86967d4928
Revises: 9caa120a4d97
Create Date: 2023-02-09 10:14:45.623338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c86967d4928'
down_revision = '9caa120a4d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('linkedin_id', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('nome', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
