"""empty message

Revision ID: 9b42b7654f69
Revises: d2004d3b7cc1
Create Date: 2023-02-10 15:45:13.070162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b42b7654f69'
down_revision = 'd2004d3b7cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conquistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('moedas', sa.String(length=120), nullable=True),
    sa.Column('dificuldade', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('insignia', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carteira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moedas', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conquistas', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_Desafios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desafio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['desafio_id'], ['desafios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_conquistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquistas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carteira_historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('moedas', sa.Integer(), nullable=True),
    sa.Column('evento', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carteira_historicos')
    op.drop_table('user_conquistas')
    op.drop_table('user_Desafios')
    op.drop_table('carteira')
    op.drop_table('conquistas')
    # ### end Alembic commands ###
