"""empty message

Revision ID: 9caa120a4d97
Revises: 48f03a0302b2
Create Date: 2023-02-09 10:00:16.853002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9caa120a4d97'
down_revision = '48f03a0302b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
