"""empty message

Revision ID: c78071fbc6ab
Revises: 9b42b7654f69
Create Date: 2023-02-10 18:43:50.986323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78071fbc6ab'
down_revision = '9b42b7654f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conquistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('moedas', sa.String(length=120), nullable=True),
    sa.Column('dificuldade', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('insignia', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desafios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('moedas', sa.String(length=120), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_final', sa.Date(), nullable=True),
    sa.Column('grupo', sa.String(length=120), nullable=True),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('situacao', sa.String(length=120), nullable=True),
    sa.Column('banner', sa.String(length=120), nullable=True),
    sa.Column('card', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('preco', sa.String(length=120), nullable=True),
    sa.Column('preco_desconto', sa.String(length=120), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('ano', sa.String(length=120), nullable=True),
    sa.Column('quantidade_estoque', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('imagem', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=120), nullable=True),
    sa.Column('linkedin_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carteira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moedas', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conquistas', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_Desafios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desafio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['desafio_id'], ['desafios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_conquistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquistas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carteira_historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('moedas', sa.Integer(), nullable=True),
    sa.Column('evento', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carteira_historicos')
    op.drop_table('user_conquistas')
    op.drop_table('user_Desafios')
    op.drop_table('carteira')
    op.drop_table('users')
    op.drop_table('produtos')
    op.drop_table('desafios')
    op.drop_table('conquistas')
    # ### end Alembic commands ###
